# Generated by Django 3.1.2 on 2020-11-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('given_date', models.DateField(auto_now=True)),
                ('question_file', models.FileField(upload_to='media/assignments/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.subject')),
            ],
        ),
    ]
