# Generated by Django 3.1.2 on 2020-11-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestion',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
