# Generated by Django 3.1.2 on 2020-11-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20201121_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestion',
            name='question_file',
            field=models.FileField(upload_to='assignments/'),
        ),
    ]
