# Generated by Django 3.1.2 on 2020-11-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20201121_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestion',
            name='slug',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
