# Generated by Django 3.1.2 on 2020-11-21 18:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_assignmentquestion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='answer_text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
