# Generated by Django 3.1.2 on 2020-11-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20201121_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='slug',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
