# Generated by Django 3.1.2 on 2020-11-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_subject'),
        ('assignment', '0008_assignmentsubmission_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestion',
            name='given_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
            preserve_default=False,
        ),
    ]
